### PR TITLE
fix: enum docs for trigger_actions

### LINKED ISSUE #147: zitadel_trigger_actions (resource) is missing 'FLOW_TYPE_INTERNAL_AUTHENTICATION' value
The documentation for `zitadel_trigger_actions` (https://github.com/zitadel/terraform-provider-zitadel/blob/f579a029d582bbdee5d777c0fd5e362dd3951dc0/docs/resources/trigger_actions.md?plain=1#L29)
is missing the `FLOW_TYPE_INTERNAL_AUTHENTICATION` value (as defined here: https://github.com/zitadel/terraform-provider-zitadel/blob/f579a029d582bbdee5d777c0fd5e362dd3951dc0/zitadel/trigger_actions/resource.go#L59)

### PR DESCRIPTION
**Pull request by stebenz**
### Definition of Ready

- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] All non-functional requirements are met
- [ ] The generic lifecycle acceptance test passes for affected resources.
- [ ] Examples are up-to-date and meaningful. The provider version is incremented.
- [ ] Docs are generated.
- [ ] Code is generated where possible.

closes #147

### CODE REVIEW

File: zitadel/helper/helper.go [hunk 1]
```diff
@@ -124,8 +124,19 @@ func GetStringFromAttr(ctx context.Context, attrs map[string]attr.Value, key str
 func DescriptionEnumValuesList(enum map[int32]string) string {
 	str := ", supported values: "
 	values := make([]string, len(enum))
-	for i := 0; i < len(enum); i++ {
-		values[i] = enum[int32(i)]
+	highest := 0
```
Comment (eliobischof) [inline zitadel/helper/helper.go:127]: I assume you are trying to sort them? Why does it not already sort correctly? We access the values by the indexed key, right?

Comment (stebenz) [reply zitadel/helper/helper.go:127]: No the problem is that ENUMs can technically start with wherever and also numbers can be left out, that's why we first have to find out which is the highest number and then go from 0 to the highest to find out which are existing.

Comment (eliobischof) [reply zitadel/helper/helper.go:127]: ok, got it

**Review by eliobischof — APPROVED** [review]
